---
- hosts: all
  become: true

  pre_tasks:
  roles:
    - role: .
      vm_build_name: "test"
      vm_build_cpu: 2
      vm_build_memory: 2048
      vm_build_disk: 20G
      vm_build_image: https://cloud-images.ubuntu.com/trusty/current/trusty-server-cloudimg-amd64-disk1.img
      vm_build_image_sha256: sha256:84339b18993f7ea4e79067e05bc2066c8c9ae69c1a6ad6fc953a0ea016860a81
      vm_build_virtualization: "qemu"
      vm_build_os_family: "Debian"
      vm_build_uuid: "ffab2cd3-b9a6-fafb-6887-d058688aa57f"
      vm_build_fqdn: "test.example.com"
      vm_build_ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDDvavjyPB+HLO7Ed5ZQT0ALx3aZU7BkII3a6BWeBP0Y40n8+P3kiaaOolPCjA4xPh0iqFyLGtTB9NFuj2NKaoEqE6be/8BHmPX00bYx+7iaJWVCPJuMH0lnBjRQYLCUC6MbrgEdNaI+KH7FDCEn9xDlJLHMrhriKVky8WOI7HVimlTuSKnwntvvAO9sd9V7sE0QGWA1sIJ1+w/sIK6YjRfE5KdyjYN0l8XaBSvhg0rn4TvxrwuM0iNB7xNw1yMKiHRcygMXHJFTPevO0ftSYHd/9biqzr4njWuFaGxsSXDO528lXzaXHJFzLrjqDlaRsmExK58j1EOFg/383bh0Rv root@qemu"
      vm_build_availability_zone: ""
      vm_build_network_info: True
      vm_build_config_dir: "/openstack/qemu/iso/config"
      vm_build_iso_dir: "/openstack/qemu/iso"
      vm_build_resolv:
        domain: "example.com"
        search: "hola.example.com"
        dns: ['8.8.8.8']
      vm_build_hosts:
        - ['127.0.1.1', 'host1.domain.com']
        - ['127.0.1.2', 'host3.domain.com']
      vm_build_network_device_list:
        - device: "eth0"
          bridgename: "virbr0"
          bootproto: "dhcp"
        - device: "eth1"
          bridgename: "virbr0"
          bootproto: "static"
          address: "10.1.1.10"
          netmask: "255.255.255.0"
          gateway: "10.1.1.1"
          nameservers: 
            - 8.8.8.8
            - 9.9.9.9
          domain: "domain.com"

#   - name: Display all variables/facts known for a host
#     debug: var=hostvars[inventory_hostname]

