---
- name: Create image directory
  file: path={{vm_build_image_dir}} state=directory

- name: Downloading image
  get_url:
    url: "{{vm_build_image}}"
    dest: "{{vm_build_image_dir}}/{{vm_build_image | basename}}"
    checksum: "{{vm_build_image_sha256}}"