---
#TODO(evrardjp): Replace the next 2 tasks by a standard apt with cache
#when https://github.com/ansible/ansible-modules-core/pull/1517 is merged
#in 1.9.x or we move to 2.0 (if tested working)
- name: Check apt last update file
  stat:
    path: /var/cache/apt
  register: apt_cache_stat
  tags:
    - repo-packages

- name: Update apt if needed
  apt:
    update_cache: yes
  when: "ansible_date_time.epoch|float - apt_cache_stat.stat.mtime > {{cache_timeout}}"
  tags:
    - repo-packages

- name: Install required packages                                                                                                                                                              
  apt:                                                                                                                                                                                            
    pkg: "{{ item }}"                                                                                                                                                                             
    state: "{{ vm_build_package_state }}"                                                                                                                                                      
  register: install_packages                                                                                                                                                                      
  until: install_packages|success                                                                                                                                                                 
  retries: 5                                                                                                                                                                                      
  delay: 5                                                                                                                                                                                        
  with_items: "{{ vm_build_distro_packages }}"                                                                                                                                                 
  tags:                                                                                                                                                                                           
    - repo-packages     